# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase-if-necessary
    groups:
      prod-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "*eslint*"
          - "*prettier*"
          - "*jest*"
          - "*vitest*"
          - "*playwright*"
        commit-message:
          prefix: "fix(deps)"
          include: "scope"
      dev-types:
        patterns:
          - "@types/*"
        commit-message:
          prefix: "build(deps-dev)"
          include: "scope"
