parser: '@typescript-eslint/parser'
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

plugins:
  - simple-import-sort

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  simple-import-sort/imports: error
  simple-import-sort/exports: error
